"""init

Revision ID: 64c7783427f9
Revises: d8308a1f0f79
Create Date: 2025-07-20 20:03:05.444185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c7783427f9'
down_revision = 'd8308a1f0f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='restaurantapprovalstatus'), nullable=False))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('approval_status')

    # ### end Alembic commands ###
